### ISSUE TITLE
User Stories 

### ISSUE THREAD

**Issue by AnthonyAllan** [mtrupia/CS481_Anthony_Anna_Michael#25]
- As a player, I want to move so that I can complete the level.
- As a player, I want to shoot so that I can kill Enemies.
- As a player, I want to pick up items so that I can pick up, [HP || Mana || Key]
- As a player, I want to restart the level so that if I get stuck, I can start over.
- As a player, I want to be able to pause so I can have a snack break while playing my favorite game.
- As a player, I want to select a different level if I chose the wrong level.
- As a player, I want to see who made the game, so I can tell them how great their game is.
- As a player, I want to exit the game so that I can close the app.
- As a developer, I want unit tests so that I can ensure the variables are correct.
- As a developer, I want a level editor, so that I can visually create levels.

**Comment by aschmedd** [comment]
- As a player, I want the game to increase in difficulty as I progress.
- As a player,  I want more mechanics as I progress in the game.
- As a player, I want to associate enemy colors with enemy type/difficulty.

**Comment by AnthonyAllan** [comment]
- As a player, I want graphics to associate to different objects [Ammo Types, Enemies, Keys/Doors]
- As a developer, I want to quickly test item functionality.

**Comment by AnthonyAllan** [comment]
Moved user stories to their own issues w/ User Stories Milestone tag.
