### ISSUE TITLE
Character Behavior

### ISSUE THREAD

**Issue by AnthonyAllan** [mtrupia/CS481_Anthony_Anna_Michael#3]
Complete code that tracks coordinates of Mollie. (Coordinates of Screen & Which grid square she is in)
Move character.

**Comment by AnthonyAllan** [comment]
The file attached contains code to move the player in parallel to your finger motion.
[Move Player.txt](https://github.com/mtrupia/CS481_Anthony_Anna_Michael/files/481329/Move.Player.txt)

**Comment by mtrupia** [comment]
Complete character movement 9/25/16

**Comment by mtrupia** [comment]
Completed character movement, world moving, and object collisions: 9/25/16
